# Generated by Django 4.1.4 on 2023-01-25 13:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coustomer_details',
            fields=[
                ('Coustomer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('ph_number', models.IntegerField()),
                ('address', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField()),
                ('order_name', models.CharField(max_length=100)),
                ('order_date', models.DateField(auto_now=True)),
                ('amount', models.IntegerField()),
                ('del_date', models.DateField(auto_now_add=True)),
                ('Coustomer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.coustomer_details')),
            ],
        ),
    ]
