# Generated by Django 4.1.4 on 2023-01-26 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='Coustomer_id',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='coustomer_details',
            name='Coustomer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='coustomer_details',
            name='name',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
